[project]
name = "litellm-prac"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.5.5",
    "fitz>=0.0.1.dev2",
    "litellm>=1.71.2",
    "openai>=1.82.0",
    "openai-agents[litellm]>=0.0.16",
]
